url: "http://korentia.com"
highlighter: pygments
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes     # footnotes

exclude: ["README.md", "_posts_TOFIX", "vendor"]

author_dir: blog/author

tag_page_layout: tag_page
tag_page_dir: blog/tag
tag_page_layout: tag

paginate: 10
paginate_path: "/blog/page:num"

sitename: "Korentia"
subtitle: "craft at heart"
email: "hola@korentia.com"

googleanalytics:
  account: UA-

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
